<<<<<<< HEAD
name = "face-recognition-worker"
=======
name = "iot"
>>>>>>> f125e58ef3481dc4b5a2862577efcc863cccbd3a
main = "src/worker.js"
compatibility_date = "2024-12-27"

[[d1_databases]]
binding = "DB"  # Nama binding di worker.js
database_name = "face-recognition-db"
database_id = "ad63ee7a-4f08-420e-bf3a-4af688096ce6"  # Database ID dari output

[vars]
API_TOKEN = "face-recognition-token-123"